# Generated by Django 4.1.3 on 2022-12-02 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal_app', '0002_service'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Interest',
            new_name='Interests',
        ),
        migrations.RenameModel(
            old_name='Service',
            new_name='Services',
        ),
    ]
