# Generated by Django 4.1.3 on 2022-12-03 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personal_app', '0004_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('image', models.ImageField(upload_to='ProductImage')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal_app.contact')),
            ],
        ),
    ]
