# Generated by Django 4.1.3 on 2022-12-06 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personal_app', '0005_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testmonials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon1', models.CharField(max_length=50)),
                ('profile', models.ImageField(upload_to='ProductImage')),
            ],
        ),
        migrations.RemoveField(
            model_name='services',
            name='description',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.AddField(
            model_name='testmonials',
            name='description',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal_app.services'),
        ),
    ]
