# Generated by Django 4.1.3 on 2022-12-06 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_app', '0007_services_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testmonials',
            name='description',
            field=models.TextField(),
        ),
    ]
