# Generated by Django 4.1.3 on 2022-12-06 14:47

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_app', '0008_alter_testmonials_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='testmonials',
            name='designation',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='testmonials',
            name='icon2',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='testmonials',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='testmonials',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='testmonials',
            name='icon1',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='testmonials',
            name='profile',
            field=models.ImageField(blank=True, null=True, upload_to='ProductImage'),
        ),
    ]
