# Generated by Django 4.1.3 on 2022-12-06 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_app', '0009_testmonials_designation_testmonials_icon2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testmonials',
            old_name='name',
            new_name='nam',
        ),
        migrations.RemoveField(
            model_name='testmonials',
            name='description',
        ),
        migrations.AddField(
            model_name='testmonials',
            name='desc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='interests',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='services',
            name='description',
            field=models.TextField(),
        ),
    ]
